- hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - creds.yml
  vars:
    - region: eu-west-2
    - image: ami-403e2524
    - vpc_subnet_id: subnet-5a2a3a21
  tasks:
    - name: Boot EC2 Instance
      ec2:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        key_name: AMIBuild
        group: AMIBuild
        instance_type: t2.micro
        image: "{{image}}"
        wait: yes
        wait_timeout: 500
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        count_tag:
          Name: AMIBuild
        exact_count: 1
      register: ec2

    - name: debug connectivity
      debug:
        msg: "ip is {{item.private_ip}}"
      with_items: "{{ ec2.instances }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.private_ip }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"


- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  remote_user: ec2-user
  connection: ssh
  roles:
    - role: myapp

