- hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - creds.yml
  vars:
    - region: eu-west-2
    - image: ami-403e2524
    - vpc_subnet_id: subnet-5a2a3a21
  tasks:
    - name: Boot EC2 Instance
      ec2:
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        key_name: AMIBuild
        group: AMIBuild
        instance_type: t2.micro
        image: "{{image}}"
        wait: yes
        wait_timeout: 500
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        count_tag:
          Name: AMIBuild
        instance_tags:
          Name: AMIBuild
        exact_count: 1
      register: ami_instance

    - name: Add new instance to host group
      add_host:
        name: "{{ ami_instance.tagged_instances.0.private_ip }}"
        groups: ec2_launched

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ ami_instance.tagged_instances.0.private_ip }}"
        port: 22
        timeout: 120

- hosts: launched
  become: True
  gather_facts: True
  remote_user: ec2-user
  roles:
    - role: myapp

