- hosts: local
  connection: local
  vars_files:
    - creds.yml
  gather_facts: no
  roles:
    - role: amibuilder
      region: eu-west-2
      image: ami-403e2524
      vpc_subnet_id: subnet-5a2a3a21
      amibuilder_mode: boot

  post_tasks:
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.private_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"


- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - role: myapp


- hosts: local
  connection: local
  vars_files:
    - creds.yml
  gather_facts: no
  roles:
    - role: amibuilder
      region: eu-west-2
      image: ami-403e2524
      vpc_subnet_id: subnet-5a2a3a21
      amibuilder_mode: bake
